apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-bigip-ctlr
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-bigip-ctlr
  template:
    metadata:
      name: k8s-bigip-ctlr
      labels:
        app: k8s-bigip-ctlr
    spec:
      # Name of the Service Account bound to a Cluster Role with the required
      # permissions
      serviceAccountName: bigip-ctlr
      containers:
        - name: k8s-bigip-ctlr
          image: f5networks/k8s-bigip-ctlr:2.1.1
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  # Replace with the name of the Secret containing your login
                  # credentials
                  name: bigip-login
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  # Replace with the name of the Secret containing your login
                  # credentials
                  name: bigip-login
                  key: password
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            # Replace with the IP address or hostname of your BIG-IP device
            "--bigip-url=10.145.73.66",
            # Replace with the name of the BIG-IP partition you want to manage
            "--bigip-partition=openshift",
            # Replace with service type - cluster or nodeport
            "--pool-member-type=nodeport",
            # set the namespace for CIS to watch.
            "--namespace=default",
            # Logging level
            "--log-level=DEBUG",
            "--log-as3-response=true",
            # Self-signed cert
            "--insecure=true",
            # Custom Resource Mode
            "--custom-resource-mode=true"
          ]
      imagePullSecrets:
        - name: f5-docker-images
        - name: bigip-login
