apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: tea-virtual-server
  namespace: default
spec:
  host: tea.example.com
  httpTraffic: redirect
  pools:
  - path: /lattee
    service: nginx
    servicePort: 80
  - path: /mocha1
    service: nginx
    servicePort: 80
  tlsProfileName: edge-tls
  virtualServerAddress: 172.16.3.5

---
apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  name: edge-tls
  labels:
    f5cr: "true"
spec:
  tls:
    termination: edge
    clientSSL: /Common/clientssl
    reference: bigip
  hosts:
  - tea.example.com
