apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: coffee-virtual-server
  namespace: default
spec:
  tlsProfileName: reencrypt-tls
  httpTraffic: redirect
  host: coffee.example.com
  pools:
    - path: /lattee
      service: nginx
      servicePort: 8080
    - path: /mocha1
      service: nginx
      servicePort: 8080
  virtualServerAddress: 172.16.3.5

---

apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  name: reencrypt-tls
  labels:
    f5cr: "true"
spec:
  tls:
    termination: reencrypt
    clientSSL: /Common/clientssl
    serverSSL: /Common/serverssl
    reference: bigip
  hosts:
  - coffee.example.com
